export const docsArticles = [
  { id: "intro", title: "Introduction to Fedora Vietnam", category: "Getting Started" },
  { id: "usb", title: "Creating a Bootable USB", category: "Installation" },
  { id: "dual-boot", title: "Standard Dual Boot with Windows", category: "Installation" },
  { id: "input", title: "Configuring Vietnamese Input", category: "System Setup" },
  { id: "docker", title: "Setting up Docker on Fedora", category: "Development" },
  { id: "chuẩn-bị-cài-đặt", title: "1) Chuẩn bị cài đặt", category: "Getting Started" },
  { id: "cấu-hình-sau-cài", title: "2) Cấu hình sau cài", category: "System Setup" },
  { id: "môi-trường-làm-việc", title: "3) Môi trường làm việc", category: "Development" },
  { id: "cài-fedora-dual-boot-với-windows", title: "Cài Fedora dual-boot với Windows", category: "Installation" },
  { id: "fix-lỗi-wi-fi,-bluetooth,-âm-thanh", title: "Fix lỗi Wi-Fi, Bluetooth, âm thanh", category: "Troubleshooting" },
  { id: "thiết-lập-môi-trường-dev-chuẩn", title: "Thiết lập môi trường Dev chuẩn", category: "Development" },
  { id: "tối-ưu-hiệu-năng-desktop-fedora", title: "Tối ưu hiệu năng desktop Fedora", category: "System Setup" }
]

export const forumTopics = [
  {
    id: "1",
    title: "Upgrading to Fedora 40: Workstation installation hangs at 80%",
    author: "linux_pioneer",
    time: "2h ago",
    category: "Installation",
    replies: 42,
    views: "1.2k",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=pioneer",
  },
  {
    id: "2",
    title: "RFC: Proposed changes to DNF package manager backend for F41",
    author: "fedora_core",
    time: "5h ago",
    category: "Development",
    replies: 128,
    views: "5.8k",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=core",
  },
  {
    id: "3",
    title: "Best laptop for Fedora 40? Looking for something with long battery life.",
    author: "hardware_enthusiast",
    time: "12h ago",
    category: "General Support",
    replies: 15,
    views: 450,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=hardware",
  },
  {
    id: "4",
    title: "Fedora 40 KDE Plasma 6: Screen flickering on Wayland with NVIDIA",
    author: "plasma_fan",
    time: "1d ago",
    category: "Bugs",
    replies: 89,
    views: "2.4k",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=plasma",
  },
]
